//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIT323_Crozzle.ServiceReferenceGroup {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceGroup.IWordGroupService")]
    public interface IWordGroupService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordGroupService/Count", ReplyAction="http://tempuri.org/IWordGroupService/CountResponse")]
        int Count(string[] grid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordGroupService/Count", ReplyAction="http://tempuri.org/IWordGroupService/CountResponse")]
        System.Threading.Tasks.Task<int> CountAsync(string[] grid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordGroupServiceChannel : SIT323_Crozzle.ServiceReferenceGroup.IWordGroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordGroupServiceClient : System.ServiceModel.ClientBase<SIT323_Crozzle.ServiceReferenceGroup.IWordGroupService>, SIT323_Crozzle.ServiceReferenceGroup.IWordGroupService {
        
        public WordGroupServiceClient() {
        }
        
        public WordGroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordGroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordGroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordGroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Count(string[] grid) {
            return base.Channel.Count(grid);
        }
        
        public System.Threading.Tasks.Task<int> CountAsync(string[] grid) {
            return base.Channel.CountAsync(grid);
        }
    }
}
